# Generated by Django 5.0.1 on 2024-02-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateField(blank=True, null=True, verbose_name="дата создания"),
        ),
    ]
